### ISSUE TITLE
add homework for dplyr lesson using gapminder data

### ISSUE THREAD

**Issue by stephenturner** [bioconnector/bims8382#2]
The dplyr lesson uses the Brauer yeast data, but the ggplot2 lesson uses the gapminder data. Write a few homework questions as a follow up to the dplyr lesson so students are familiar with the gapminder data prior to the ggplot2 lesson.
- discuss the variables in the data
- load the data with `readr::read_csv`
- review dplyr verbs

Use the existing dplyr lesson (http://bioconnector.org/workshops/lessons/r/r-manipulation/) as a guide.

**Comment by vpnagraj** [comment]
just submitted a pull request with the dplyr hw:

https://github.com/bioconnector/bims8382/pull/5

**Comment by stephenturner** [comment]
closed in pr #5
